<?php

/**
 * @file
 * Contains oembedly.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function oembedly_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oembedly module.
    case 'help.page.oembedly':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Oembedly') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function oembedly_theme() {
  return [
    'oembedly' => [
      'template' => 'oembedly',
      'variables' => ['info' => NULL, 'code' => NULL],
    ],
  ];
}
